### ISSUE TITLE
cant add user or change password

### ISSUE THREAD

**Issue by panickspa** [os-js/osjs-database-auth#1]
hey there, i'm new on using npx-cli, i got eror on this
![capture](https://user-images.githubusercontent.com/39858113/51423574-f5b8a600-1bf4-11e9-9f41-dcf2f235826f.JPG)

**Comment by andersevenrud** [comment]
Seems like a change in `@osjs/cli` might have broken this. I'm fixing this ASAP.

**Comment by andersevenrud** [comment]
I published a new version of `@osjs/database-auth` that fixes this issue.
