### ISSUE TITLE
How to use sqlite as db

### ISSUE THREAD

**Issue by erfan-azhdari** [os-js/osjs-database-auth#4]
I want to use sqlite as a db like the  [previous version of os-js](https://manual.os-js.org/v2/configuration/authenticator/database/#sqlite)

**Comment by andersevenrud** [comment]
Change your connection options to

```
  type: 'sqlite',
  database: 'path/to/database.sqlite'
```

and install `npm install sqlite3`, and it should work.

**Comment by andersevenrud** [comment]
Let me know how it works out. Not sure I've tested this myself (but TypeORM should support it out of the box) :)

**Comment by erfan-azhdari** [comment]
I dont know check #5.

**Comment by erfan-azhdari** [comment]
it works!

**Comment by erfan-azhdari** [comment]
can you add this to the documention or readme?

**Comment by andersevenrud** [comment]
Great! Sure, I can add some more information.

**Comment by andersevenrud** [comment]
I've updated the documentation in the following commit: https://github.com/os-js/osjs-database-auth/commit/12d702550285d17674d4d6e65b859c80052d7570

I also updated https://github.com/os-js/osjs-database-settings to reflect this as well.

**Comment by erfan-azhdari** [comment]
Thanks!
