### ISSUE TITLE
Invalid command: npx osjs-cli user:add

### ISSUE THREAD

**Issue by erfan-azhdari** [os-js/osjs-database-auth#5]
my problem looks like #3.
when I run the command `npx osjs-cli user:add --username=anders` (the example in readme)
it says :
`Invalid command: user:list`
`See --help for a list of available commands.`

I installed everything about an hour ago and I ran `npm update` and `npm update @osjs/osjs-database-auth`

[here](https://paste.ubuntu.com/p/gVq4RggvQK/)'s the my `src/server/index.js`
and [this](https://paste.ubuntu.com/p/6Nwx4bxmv5/) is my `src/client/config.js`
and [this](https://paste.ubuntu.com/p/TRZsnbbfxk/) is the output of `npx osjs-cli info`

**Comment by andersevenrud** [comment]
Have you updated your CLI script ?

https://github.com/os-js/osjs-database-auth#configure-cli

**Comment by erfan-azhdari** [comment]
I did but I forgot to add `dbCli` to  the `tasks` array.
I fixed it and it worked.
thanks for your fast response.

**Comment by andersevenrud** [comment]
Great! No problem
